import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["greek"] });

export const metadata = {
  title: "PustakaKu",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/logo-hr.png" sizes="any" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
